// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Test1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test1() {
    driver.get("https://www.calculator.net/");
    driver.manage().window().setSize(new Dimension(648, 639));
    driver.findElement(By.xpath("//span[@onclick=\'r(8)\']")).click();
    driver.findElement(By.xpath("//span[@onclick=\'r(5)\']")).click();
    driver.findElement(By.xpath("//span[@onclick=\"r(\'*\')\"]")).click();
    driver.findElement(By.xpath("//span[@onclick=\'r(5)\']")).click();
    driver.findElement(By.xpath("//span[@onclick=\"r(\'=\')\"]")).click();
    assertThat(driver.findElement(By.id("sciOutPut")).getText(), is(" 425"));
    {
      WebElement element = driver.findElement(By.xpath("//html"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.xpath("//html"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.xpath("//html"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.linkText("Percentage Calculator")).click();
    driver.findElement(By.id("cpar1")).click();
    driver.findElement(By.id("cpar1")).sendKeys("258");
    driver.findElement(By.id("cpar2")).click();
    driver.findElement(By.id("cpar2")).sendKeys("10000");
    driver.findElement(By.xpath("//input[@value=\'Calculate\']")).click();
    assertThat(driver.findElement(By.cssSelector("b:nth-child(1)")).getText(), is("25800"));
  }
}
